Feature/add validations
admin-ch/CovidCertificate-Notification-Service pull request #4
Opened 2022-03-04 10:45 UTC by ndinat

- added validations
- removed authentication
- added tests
- modified deletion logic: notifications have explicitly to be deleted first in order to overwrite them

2022-03-07 12:42 UTC, haraldloesing reviewed
Ich denke über ein paar Details müssen wir noch reden.

2022-03-07 12:42 UTC, haraldloesing commented on src/main/java/ch/admin/bag/covidcertificate/api/request/MessageDto.java
> +import static ch.admin.bag.covidcertificate.api.Constants.*;
Import Korrektur im IntelliJ noch einstellen, das * imports vermieden werden.

2022-03-07 12:42 UTC, haraldloesing commented on src/main/java/ch/admin/bag/covidcertificate/api/validation/StartBeforeEndValidator.java
> +        LocalDateTime start = (LocalDateTime) new BeanWrapperImpl(value)
Die Häufigkeit der Eingabe einer Notification ist sehr gering, aber generell wird hier doch das DTO validiert und Dort haben wir bereits ein LocalDateTime. Generische Validierung ist schön, aber hier stören mich die 2 BeanWrapperImpl Instanzen um aus Object ein LocalDateTime zu machen.

2022-03-07 12:42 UTC, haraldloesing commented on src/main/java/ch/admin/bag/covidcertificate/web/controller/NotificationsController.java
> -    @PreAuthorize("hasAnyRole('bag-cc-certificatecreator', 'bag-cc-superuser')")
Hier fehlt ja jetzt die Authentication. D.h. jeder der das UI ein wenig analysiert kann eine Wartung aktivieren. Richtig?

2022-03-07 13:48 UTC, mofobo-bit commented on src/main/java/ch/admin/bag/covidcertificate/api/Constants.java
> +    public static final NotificationError NOTIFICATION_ALREADY_EXISTING_ERROR = new NotificationError(552, "There are already existing notifications which have to be removed first in order to write n
Stay in the 4xx range.

2022-03-07 13:50 UTC, mofobo-bit commented on src/main/java/ch/admin/bag/covidcertificate/api/exception/ResponseStatusExceptionHandler.java
> +        var message = "";
Give a default message if 'violation' message not present.

2022-03-07 14:15 UTC, mofobo-bit requested changes

2022-03-07 14:15 UTC, mofobo-bit commented on src/main/java/ch/admin/bag/covidcertificate/api/request/MessageDto.java
> +    private String en;
Use @NotBlank to avoid empty OR white-spaces-only properties.

2022-03-07 14:15 UTC, mofobo-bit commented on src/main/java/ch/admin/bag/covidcertificate/api/request/NotificationDto.java
> +@Setter
I think @Data could replace all those four annotations.

2022-03-07 14:15 UTC, mofobo-bit commented on src/main/java/ch/admin/bag/covidcertificate/api/validation/StartBeforeEndValidator.java
> +public class StartBeforeEndValidator
Go with class validator instead of generic.

2022-03-07 14:15 UTC, mofobo-bit commented on src/main/java/ch/admin/bag/covidcertificate/service/NotificationService.java
> +        if ((!this.notificationRepository.findAll().isEmpty())) {
I recommand the use of '.count()', for this purpose 'findAll()' is a heavy operation.

2022-03-16 13:14 UTC, haraldloesing commented on src/main/java/ch/admin/bag/covidcertificate/api/validation/StartBeforeEndValidator.java
> +public class StartBeforeEndValidator
done

2022-03-16 13:14 UTC, haraldloesing commented on src/main/java/ch/admin/bag/covidcertificate/web/controller/NotificationsController.java
> -    @PreAuthorize("hasAnyRole('bag-cc-certificatecreator', 'bag-cc-superuser')")
done

2022-03-21 08:36 UTC, haraldloesing approved these changes

2022-03-21 15:31 UTC, mofobo-bit requested changes

2022-03-21 15:31 UTC, mofobo-bit commented on src/main/java/ch/admin/bag/covidcertificate/web/controller/NotificationsController.java
> +@Validated
I think it also work without "@Validated" since "@Valid" is sufficient to activate the validation. To be verified.

2022-03-21 15:31 UTC, mofobo-bit commented on src/test/java/ch/admin/bag/covidcertificate/api/validation/NotInPastValidatorTest.java
> +    public void ifDateIsNull_thenReturnTrue() {
I recommend you the usage of @DisplayName, e.g. :
@DisplayName("Given date is 'null', when validated, it should return 'true'")

2022-03-21 15:31 UTC, mofobo-bit commented on src/test/java/ch/admin/bag/covidcertificate/api/validation/NotInPastValidatorTest.java
> +    private final LocalDateTime now = LocalDateTime.now();
'now' is not used.

2022-03-21 15:31 UTC, mofobo-bit commented on src/test/java/ch/admin/bag/covidcertificate/api/validation/NotInPastValidatorTest.java
> +class NotInPastValidatorTest {
Can you add a test for 'now'?

2022-03-21 15:31 UTC, mofobo-bit commented on src/main/resources/application-abn.yml
> +  cache-duration: 21600000
'cache-duration' is never used (verify all application.yml files)

2022-03-23 14:18 UTC, ndinat commented on src/main/java/ch/admin/bag/covidcertificate/web/controller/NotificationsController.java
> +@Validated
Nope, it's needed as far as I can tell.

2022-03-23 14:18 UTC, ndinat commented on src/test/java/ch/admin/bag/covidcertificate/api/validation/NotInPastValidatorTest.java
> +    public void ifDateIsNull_thenReturnTrue() {
Done

2022-03-23 14:18 UTC, ndinat commented on src/test/java/ch/admin/bag/covidcertificate/api/validation/NotInPastValidatorTest.java
> +    private final LocalDateTime now = LocalDateTime.now();
Removed

2022-03-23 14:18 UTC, ndinat commented on src/test/java/ch/admin/bag/covidcertificate/api/validation/NotInPastValidatorTest.java
> +class NotInPastValidatorTest {
Done

2022-03-23 14:19 UTC, ndinat commented on src/main/resources/application-abn.yml
> +  cache-duration: 21600000
removed

2022-03-28 14:36 UTC, merged